image: docker-registry.univ-nantes.fr/sunye-g/docker-asciidoctor-revealjs

stages:
  - build
  - deploy
  
build:
  stage: build
  script:
   - bash /home/compile.sh
  artifacts:
    paths:
      - target

pages:
  stage: deploy
  script:
   - mkdir -p public
   - rsync -r target/site/ public
  artifacts:
    paths:
      - public
  only:
    - master