image: node:13

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - npm install
  - npm run bower

pages:
  stage: deploy
  script:
  - npm run dist
  - mv dist public
  artifacts:
    paths:
    - public
  only:
  - master