@startuml class-adapter


hide circle

skinparam class {
    BackgroundColor white
    ArrowColor black
    BorderColor black
}

skinparam note {
    BackgroundColor lightyellow
    ArrowColor black
    BorderColor black
}

skinparam nodesep 90

class Client{
}

interface /Target <<interface>> {
    /request()*
}

class /Adapter {
    /request()*
}

class /Adaptee {
    /specificRequest()
}

Client -right-> "1" "/Target"

"/Adapter" .up.|> "/Target"

"/Adapter" -right-|> "/Adaptee"

note bottom of "/Adapter": Adapter::request()\n this.specificRequest()

@enduml