@startuml object-adapter

' left to right direction

hide circle

skinparam class {
    BackgroundColor white
    ArrowColor black
    BorderColor black
}

skinparam note {
    BackgroundColor lightyellow
    ArrowColor black
    BorderColor black
}

skinparam nodesep 90

class Client{
}

interface /Target <<interface>> {
    /request()*
}

class /Adapter {
    /request()*
}

interface /Adaptee <<interface>> {
    /specificRequest()
}


Client -right-> "1" "/Target"
"/Adapter" .up.|> "/Target"
"/Adapter" -right-> "1 adaptee" "/Adaptee"

note bottom of "/Adapter": Adapter::request()\n adaptee.specificRequest()

@enduml